add files from kade engine 1.5.4 (not 1.7 because the error occurs)
C:/HaxeToolkit/haxe/lib/linc_luajit/git/linc/linc_lua.h:5:19: fatal error: C:/Users/TheLeerName/Documents/GitHub/Kade-Engine-android/export/debug/android/obj/obj/android-debug-v7/__pch/haxe/hxcpp.h: No such file or directory
 #include <hxcpp.h>